/* Собственные описания и технические рекомендации для каталога. Источник моделей — 3DToday. */
(() => {
  const grid=document.querySelector('.catalog-grid'), filters=document.querySelector('.filters');
  if(!grid||!filters)return;
  [['office','Офис'],['kitchen','Кухня'],['mechanics','Механика'],['hobby','Хобби'],['gifts','Подарки'],['printer','Для 3D-принтеров']].forEach(([key,label])=>{if([...filters.children].some(b=>b.dataset.filter===key))return;const b=document.createElement('button');b.type='button';b.dataset.filter=key;b.textContent=label;filters.appendChild(b)});
  const name=el=>el.querySelector('h3')?.textContent.trim()||'';
  const classify=n=>{n=n.toLowerCase();if(/шестер|сцеплен|втул|механизм|редукт|селектор|направляющ/.test(n))return['mechanics','Механика'];if(/динамик|датчик|парктроник|панель|2din/.test(n))return['tech','Электроника'];if(/клипс|защёл|защел|креплен|кронштейн|держател|ручк|заглуш|проставк|рамк|ремкомплект|дворник|ступиц|фильтр|воздухозабор/.test(n))return['auto','Авто'];if(/подстакан|органайзер|контейнер|бардач|полк|подлокотник/.test(n))return['home','Для дома'];return['home','Для дома']};
  const material=n=>/шестер|втул|клипс|защёл|защел|креплен|кронштейн|ремкомплект/.test(n.toLowerCase())?'PETG / ABS':/ручк|подлокотник|подстакан|органайзер/.test(n.toLowerCase())?'PETG':'PLA / PETG';
  const desc=n=>{const x=n.toLowerCase();if(/шестер/.test(x))return'Функциональная замена изношенной детали механизма. Перед изготовлением рекомендуется проверить посадочные размеры и совместимость.';if(/клипс|защёл|защел/.test(x))return'Ремонтная деталь для восстановления штатного крепления. Перед печатью важно сверить геометрию с оригиналом.';if(/кронштейн|креплен|держател/.test(x))return'Практичный элемент крепления для восстановления или модернизации конструкции. Материал подбирается по нагрузке и температуре эксплуатации.';if(/ручк|подлокотник|подстакан|органайзер/.test(x))return'Функциональное изделие для салона или бытового использования. Материал и параметры печати можно подобрать под условия эксплуатации.';return'Готовая модель для изготовления на 3D-принтере. Перед печатью рекомендуется проверить размеры, посадки и соответствие конкретной версии изделия.'};
  [...grid.querySelectorAll('.product')].forEach(card=>{const n=name(card),[cat,label]=classify(n);card.dataset.cat=cat;const info=card.querySelector('.product-info');if(!info||info.querySelector('.catalog-specs'))return;const s=document.createElement('div');s.className='catalog-specs';s.innerHTML=`<p>${desc(n)}</p><div><span>Материал</span><b>${material(n)}</b></div><div><span>Технология</span><b>FDM</b></div>`;const c=info.querySelector('.model-credit');c?c.before(s):info.appendChild(s);const meta=info.querySelector('span');if(meta)meta.textContent=`${label} · FDM`});
  const input=document.querySelector('#catalogSearch');let active='all',q='';
  const apply=()=>{const all=[...grid.querySelectorAll('.product')],term=q.toLowerCase();let visible=0;const matches=all.filter(p=>(active==='all'||p.dataset.cat===active)&&(!term||p.textContent.toLowerCase().includes(term)));all.forEach(p=>p.style.display='none');matches.forEach(p=>{if(visible<10)p.style.display='';visible++});let more=document.querySelector('#catalogMore');if(!more){more=document.createElement('button');more.id='catalogMore';more.className='catalog-more';more.type='button';grid.after(more);more.onclick=()=>{more.dataset.expanded=more.dataset.expanded!=='true';apply()}}if(more.dataset.expanded==='true')matches.forEach(p=>p.style.display='');more.style.display=matches.length>10?'flex':'none';more.textContent=more.dataset.expanded==='true'?'Свернуть':'Показать ещё'};
  filters.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{filters.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');active=b.dataset.filter;const m=document.querySelector('#catalogMore');if(m)m.dataset.expanded='false';apply()}));
  if(input)input.addEventListener('input',e=>{q=e.target.value;const m=document.querySelector('#catalogMore');if(m)m.dataset.expanded='false';apply()});apply();
})();
