/* Каталог моделей. Реальные изображения из списка пользователя. */
(() => {
  const models = [
    ['Настенный органайзер','home','Бесплатная модель','Евгениваныч','free','https://3dtoday.ru/3d-models/for-office/organizers/nastennyi-organaizer','Модульный настенный органайзер для инструментов и принадлежностей.','https://3dtoday.ru/cache/640x/models/images/f6F8CiV1mmiOpk69SrdvdiYkqd8MX6KKbcLIJje1.jpg'],
    ['Органайзер под сверла и биты','office','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/for-office/organizers/organaizer-pod-sverla-i-bity','Практичный органайзер для хранения сверл, бит и мелкого инструмента.','https://3dtoday.ru/upload/models/images/4eLLbjwvbcL5cbL3u8rE0NjMMDOJ1w01PeTj7pv4.jpg'],
    ['Органайзер для инструментов','office','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/for-office/organizers/organayzer_dlya_instrumentov','Органайзер для небольшого инструмента и расходников.','https://3dtoday.ru/cache/640x/iblock/246/2463c026f4424b81ef644685e77156cb.png'],
    ['Органайзер проводов','office','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/for-office/organizers/organayzer-provodov','Компактное решение для аккуратной укладки проводов на рабочем месте.','https://3dtoday.ru/cache/640x/models/images/DwzFMhubnk5eczcMilgz4emcSZBFbXMWvvSX3MrS.jpeg'],
    ['Держатель телефона (Phone Holder)','tech','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/gadgets/phones/derzhatel_telefona_phone_holder','Простой держатель телефона для печати на FDM-принтере.','https://3dtoday.ru/cache/640x/iblock/6b4/6b449094fc1b4e23ba0c27a626d9d115.jpeg'],
    ['Держатель телефона в автомобиль','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/derzatel-telefona-v-avtomobil','Автомобильный держатель телефона для самостоятельной печати.','https://3dtoday.ru/cache/640x/models/images/7qgwnAF4zlUSU5Vqwc3VzHLsCPY0QqQNW1ZP1XZa.png'],
    ['Держатель телефона в машину - ver.2','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/gadgets/phones/derzhatel_telefona_v_mashinu_ver_2','Вариант автомобильного держателя телефона для 3D-печати.','https://3dtoday.ru/cache/640x/iblock/fde/fde99bfc4344b409da11eaffb1c7b305.jpeg'],
    ['Автомобильный держатель телефона','auto','Бесплатная модель','Евгениваныч','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/avtomobilnyi-derzatel-telefona','Модель автомобильного держателя с разборной конструкцией.','https://3dtoday.ru/cache/640x/models/images/58yrRbc9zPwXuKuOerbRldSCjsVwM0xormhAcwOj.jpg'],
    ['Toyota Mark 2 JZX90','auto','Платная модель','levbols','paid','https://3dtoday.ru/market/games/toys/toyota-mark-2-jzx90','Масштабная модель Toyota Mark 2 JZX90 для 3D-печати.','https://3dtoday.ru/cache/x480/models_store/images/Wdj2AwTSLtYhtjyZrrEN7ayioKNc4z9LnopAM86h.jpg'],
    ['Toyota Mark 2 JZX/GX110 1:24','auto','Платная модель','Maksgrande9090','paid','https://3dtoday.ru/market/khobbi/avtomobili/toyota-mark-2-jzx-gx-110-3d-model-dlya-pecati','Детализированная модель Toyota Mark 2 в масштабе 1:24.','https://3dtoday.ru/upload/models_store/images/7pNpCLo2v082rO5Pv1RWJI45iKxN41q3v7bySk93.jpg'],
    ['Автомобиль Lada Iskra 1:10','auto','Платная модель','tasya.dementieva@yandex.ru','paid','https://3dtoday.ru/market/khobbi/avtomobili/avtomobil-lada-iskra-lada-iskra','Модель Lada Iskra в масштабе 1:10.','https://3dtoday.ru/cache/x480/models_store/images/FRQykQVE65pAGj9ps85OntUoJZfZ2w5iwt7dMcrO.jpg'],
    ['Lada Kalina 1117 Universal','auto','Платная модель','GENBAYLAR','paid','https://3dtoday.ru/market/khobbi/avtomobili/lada-kalina-1117-universal-realistic-3d-car-model-lada-kalina-1117-universal-realisticnaya-3d-model-avtomobilya','Детализированная модель Lada Kalina 1117 Universal.','https://3dtoday.ru/cache/x480/models_store/images/1GNSL9fm14UXEFJLaST4PBEYTPCLHI7vyJH5qbFy.jpg'],
    ['Lada Kalina 1119','auto','Платная модель','pumazloy','paid','https://3dtoday.ru/market/khobbi/avtomobili/lada-kalina-1119','Масштабная модель Lada Kalina.','https://3dtoday.ru/cache/x480/models_store/images/1xAJ5ZCoi46fNYaaYqXTcUQiDjQ3QnOCfmttFva0.jpg'],
    ['Брелок Toyota Mark 2','gifts','Платная модель','andrey165','paid','https://3dtoday.ru/market/khobbi/avtomobili/brelok_toyota_mark_2','Небольшая модель-брелок Toyota Mark 2.','https://3dtoday.ru/upload/iblock/4b5/4b52fd4872eae4012d70fd37a7b487bb.png'],
    ['Корпус ручки Derways Ayrora 2007','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/korpus-rucki-derways-ayrora-2007','Корпус ручки для Derways Ayrora 2007.','https://3dtoday.ru/cache/640x/models/images/cVQDCJdLlvZu9DWb7dWFtpoZMNM6X79yVT4kj1va.png'],
    ['Рамка под 2DIN магнитолу для ГАЗ 24 «Волга»','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/ramka-pod-2din-magnitolu-dlya-gaz-24-volga','Рамка для установки 2DIN магнитолы в ГАЗ 24 «Волга».','https://3dtoday.ru/cache/640x/models/images/nJM89gNb2b3HedmBxARqXItJTUnzAjmUsYa0y28o.jpg'],
    ['Проставка для динамика 13см (16см → 13см)','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/prostavka-dlya-dinamika-13sm-perexodnoe-kolco-s-16sm-na-13sm','Переходное кольцо для установки динамика 13 см.','https://3dtoday.ru/cache/640x/models/images/xxZe34q4V1hKweJs3VZF7fH4xI6qvQfaejnKK28Z.png'],
    ['Упор штанги капота TOYOTA PASSO','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/upor-stangi-kapota-toyota-passo','Упор штанги капота для Toyota Passo.','https://3dtoday.ru/cache/640x/models/images/a4XukmiLmsU0U0cX61UbmivOzTJYWoqN3ofBb8eB.jpg'],
    ['Ручка капота Nissan V3','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/rucka-kapota-nissan-v3','Ручка капота для автомобиля Nissan.','https://3dtoday.ru/cache/640x/models/images/S0nchUDHHIgFGE4GZVKSXc7oh0I8SZmROaQ2jz6p.jpg'],
    ['Накладка заднего фонаря Wenbox U2 (scan)','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/nakladka-zadnego-fonarya-wenbox-u2-scan','Накладка заднего фонаря по сканированной геометрии.','https://3dtoday.ru/cache/640x/models/images/kWSYNuGAyGWTUBPCQLBVEX7XEW5uYIVUN61I7evT.png'],
    ['Toyota ISIS крепление капота','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/toyota-isis-kreplenie-kapota','Крепление капота для Toyota ISIS.','https://3dtoday.ru/cache/640x/models/images/SuQzaq0mREJu9D1LA0KjjS4X5mO2CFbI8S3a9aMV.png'],
    ['Заглушка фаркопа Westfalia','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/zagluska-farkopa-westfalia','Заглушка фаркопа Westfalia.','https://3dtoday.ru/cache/640x/models/images/elSovVpDhh6RJFgHETig3YTHjZp45TKoCl8jptFN.jpg'],
    ['Проставка для ПТФ Лада Гранта','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/prostavka-dlya-ptf-lada-granta','Проставка для противотуманной фары Лада Гранта.','https://3dtoday.ru/cache/640x/models/images/DA28Om09Pq2RjxWCFs4iPUuF9xxuAHGPfAKYy8GL.png'],
    ['Декоративный ободок селектора Nissan Qashqai J10','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/dekorativnyi-obodok-selektora-nissan-qashqai-j10','Декоративный ободок селектора Nissan Qashqai J10.','https://3dtoday.ru/cache/640x/models/images/75PvzRvvFxzn6bREReMuIQKFCEYoygfFz0yaeU0n.png'],
    ['Накладка на петлю замка лендровера','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/nakladka-na-petlyu-zamka-lendrovera','Накладка на петлю замка Land Rover.','https://3dtoday.ru/cache/640x/models/images/1r3VFX2vz2keAk34FLqT4NMJvkBHwJDyNIPkqdlm.png'],
    ['Клипса бампера Corolla E100-E104','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/klipsa-bampera-corolla-e100-e104','Клипса крепления бампера Toyota Corolla E100-E104.','https://3dtoday.ru/cache/640x/models/images/7Ky6I99TlTRgIyjN6RX1FsEF9Ff79c0lnXchB1pv.png'],
    ['Шестерня редуктора люка Toyota Mark II JZX90 / Vista SV32','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/sesternya-reduktora-lyuka-toyota-mark-ii-jzx90-vista-sv32','Шестерня редуктора люка для Toyota Mark II JZX90 / Vista SV32.','https://3dtoday.ru/cache/640x/models/images/Zs427cdgR7QqnfalwgRKOqcgRrCRmlIdfOFBnoON.png'],
    ['Кронштейн воздухозаборника Toyota','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/kronstein-vozduxozabornika-toyota','Кронштейн воздухозаборника Toyota.','https://3dtoday.ru/cache/640x/models/images/JJxY38NE7sLqKxupGIH20U5be42w8uYrySimV7XW.jpg'],
    ['Рамка, держатель зеркала Mitsubishi Galant 8 / Legnum','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/ramka-derzatel-zerkala-mitsubishi-galant-8-legnum','Рамка и держатель зеркала Mitsubishi Galant 8 / Legnum.','https://3dtoday.ru/cache/640x/models/images/7BPUylhndzHlXC7fXSSUjjYIVB4EX8QkqpjEd8mU.jpg'],
    ['Кронштейн троса отопителя Chevrolet Lacetti','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/kronstein-trosa-otopitelya-chevrolet-lacetti','Кронштейн троса отопителя Chevrolet Lacetti.','https://3dtoday.ru/cache/640x/models/images/b08aDh0LthUVmV7wpFFJsuAY9ns9YNALdV8bnsX1.png'],
    ['Защелка подлокотника Polo Sedan','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/zashhelka-podlokotnika-polo-sedan','Защелка подлокотника Volkswagen Polo Sedan.','https://3dtoday.ru/cache/640x/models/images/b0YVsvtsoug0G7OwufYEqPqTopFbXySxYoSuzOAQ.jpg'],
    ['Кронштейн фары Nissan Avenir','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/kronstein-fary-nissan-avenir','Кронштейн фары Nissan Avenir.','https://3dtoday.ru/cache/640x/models/images/WVnT8FfRq1tdbglGCfLmofMMyMHE826R8ZUACIaD.png'],
    ['Направляющая сдвижной двери Honda Stepwgn RP3 72508-SZW-003','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/napravlyayushhaya-sdviznoi-dveri-honda-stepwgn-rp3-72508-szw-003','Направляющая сдвижной двери Honda Stepwgn RP3.','https://3dtoday.ru/cache/640x/models/images/GEEhZOz4RKa7Cr4rQbWvJ9vS23NKad09NHrLinf8.jpg'],
    ['Защелка подлокотника Great Wall Hover H5','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/zashhelka-podlokotnika-great-wall-hover-h5','Защелка подлокотника Great Wall Hover H5.','https://3dtoday.ru/cache/640x/models/images/JzFrfIbz0Ld2jYMNyxZBljNVvnEauv38eOEmk8nd.jpg'],
    ['Заглушка болта M10 ремня безопасности Peugeot 408','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/kolpak-bolta-m10-remnya-bezopasnosti','Заглушка болта M10 ремня безопасности для Peugeot 408 и других авто.','https://3dtoday.ru/cache/640x/models/images/Lu6nc3tRbHwPhSlmCvnhFDTo153jRaoIGVpYxgUo.jpg'],
    ['Защелка подлокотника Lacetty','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/zashhelka-podlokotnika-lacetty','Защелка подлокотника Chevrolet Lacetti.','https://3dtoday.ru/cache/640x/models/images/rtNnqB8nBCbo2nEPecPtwfo9hfarMjFVX8OavIhz.png'],
    ['Solyris 2 TS-1639R проставки задних колонок','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/solyris-2-ts-1639r-prostavki-zadnix-kolonok','Проставки задних колонок Solyris 2 TS-1639R.','https://3dtoday.ru/cache/640x/models/images/LuI72EFgUd7LHRkzflIkYy4jlAUyUdN4akfze9zU.png'],
    ['Облицовка штатной магнитолы (ШГУ) УАЗ Патриот 2016+','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/oblicovka-statnoi-magnitoly-sgu-uaz-patriot-2014','Облицовка штатной магнитолы УАЗ Патриот.','https://3dtoday.ru/cache/640x/models/images/KJLJ20vtK6DCif7YcLhR4APNRo8EyZDv6lPmPrvC.jpg'],
    ['Проставка для динамиков с 16см на 13','auto','Бесплатная модель','3DToday','free','https://3dtoday.ru/3d-models/khobbi/avtomobili/prostavka-dlya-dinamikov-s-16sm-na-13','Переходная проставка для динамиков с 16 см на 13 см.','https://3dtoday.ru/cache/640x/models/images/bfOrRlo6e0TliCBk5tuY8yh3GLeCRGAba0gn27mv.jpg']
  ];
  const grid=document.querySelector('.catalog-grid'), filters=document.querySelector('.filters');
  if(!grid||!filters)return;
  const search=document.querySelector('.catalog-search')||document.createElement('div');
  search.className='catalog-search';
  search.innerHTML='<span>⌕</span><input id="catalogSearch" type="search" placeholder="Поиск модели, марки или детали…" autocomplete="off"><button type="button" id="clearCatalogSearch">×</button>';
  if(!search.parentNode)filters.parentNode.insertBefore(search,filters);
  grid.innerHTML=models.map(([name,cat,meta,author,type,url,description,image],i)=>`<article class="product" data-cat="${cat}" data-type="${type}" data-name="${(name+' '+author+' '+description).toLowerCase()}"><div class="product-image has-real-image"><a href="${url}" target="_blank" rel="noopener noreferrer" aria-label="Открыть ${name} на 3DToday"><img src="${image}" alt="${name}" loading="lazy" referrerpolicy="no-referrer"><div class="model-label"><b>${type==='paid'?'ПЛАТНАЯ':'БЕСПЛАТНАЯ'}</b><small>Реальное фото модели</small></div></a></div><div class="product-info"><span>${cat==='auto'?'Авто':cat==='home'?'Для дома':cat==='office'?'Офис':cat==='tech'?'Электроника':cat==='gifts'?'Подарки':'Модели'} · ${meta}</span><h3>${name}</h3><p class="catalog-description">${description}</p><div class="model-credit"><small>Автор: ${author}</small><small>Источник: 3DToday</small></div><div class="model-actions"><a href="${url}" target="_blank" rel="noopener noreferrer">Фото и модель на 3DToday →</a><b>${type==='paid'?'Платная модель':'Бесплатная модель'}</b></div></div></article>`).join('');
  filters.innerHTML=[['all','Все'],['free','Бесплатные'],['paid','Платные'],['home','Для дома'],['auto','Авто'],['tech','Электроника'],['office','Офис'],['gifts','Подарки']].map(([id,label],i)=>`<button class="${i===0?'active':''}" data-filter="${id}">${label}</button>`).join('');
  const products=[...grid.querySelectorAll('.product')];let active='all',query='';
  const apply=()=>{let visible=0;products.forEach(p=>{const ok=(active==='all'||p.dataset.type===active||p.dataset.cat===active)&&(!query||p.dataset.name.includes(query));p.style.display=ok?'':'none';if(ok)visible++});let empty=grid.querySelector('.catalog-empty');if(!visible){if(!empty){empty=document.createElement('div');empty.className='catalog-empty';empty.textContent='По вашему запросу ничего не найдено.';grid.appendChild(empty)}empty.style.display='block'}else if(empty)empty.style.display='none'};
  filters.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{filters.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');active=b.dataset.filter;apply()}));
  const input=search.querySelector('#catalogSearch');input.addEventListener('input',e=>{query=e.target.value.trim().toLowerCase();apply()});search.querySelector('#clearCatalogSearch').onclick=()=>{input.value='';query='';apply();input.focus()};
  apply();
})();
