(() => {
  const services = {
    '3d-печать': {accent:'#00bfff', image:'assets/3Dpechat 600х600.png', intro:'Изготавливаем детали, корпуса, крепления, прототипы и готовые изделия по вашей 3D-модели или помогаем подготовить модель к печати.', items:['FDM-печать PLA, PETG, ABS/ASA и другими материалами','Подбор материала под нагрузку, температуру и назначение','Единичные детали и небольшие серии','Подготовка модели, ориентация и настройка печати'], fits:'Корпуса, крепления, автомобильные детали, органайзеры, прототипы, декоративные изделия.', process:'Получаем модель → проверяем геометрию → согласовываем параметры → печатаем → выполняем постобработку при необходимости.'},
    'фотополимер': {accent:'#5f9dff', image:'assets/fotopolimer.png', intro:'Высокоточная фотополимерная печать там, где важны мелкие детали, гладкая поверхность и аккуратная геометрия.', items:['Высокая детализация мелких элементов','Гладкая поверхность после обработки','Миниатюры, мастер-модели и декоративные изделия','Выбор смолы под прочность и внешний вид'], fits:'Миниатюры, статуэтки, мастер-модели, корпуса и детали сложной геометрии.', process:'Проверяем модель → выбираем смолу и ориентацию → печатаем → промываем и засвечиваем → выполняем финишную обработку.'},
    'чпу-фрезеровка': {accent:'#ff087d', image:'assets/cnc.png', intro:'Изготавливаем детали и декоративные элементы на ЧПУ по чертежу, эскизу или цифровой модели.', items:['Фрезеровка дерева, пластика, композитов и подходящих металлов','Раскрой и обработка листовых материалов','Гравировка, выборка и контурная обработка','Подбор инструмента и режимов под материал'], fits:'Панели, таблички, декоративные элементы, проставки, корпуса и технические детали.', process:'Получаем чертёж или модель → готовим управляющую программу → согласовываем материал → выполняем обработку → проверяем результат.'},
    'рисование на холсте': {accent:'#ffd400', image:'assets/canvas.png', intro:'Создаём картины и авторские работы на холсте по вашему эскизу, фотографии, референсу или собственной идее.', items:['Картины по вашему сюжету или референсу','Портреты и декоративные композиции','Подбор формата, палитры и стилистики','Работы под интерьер или подарок'], fits:'Дом, офис, подарок, интерьерные композиции, памятные и авторские работы.', process:'Обсуждаем идею → согласовываем эскиз и стиль → выполняем работу → показываем результат → подготавливаем к передаче.'},
    'аэрография': {accent:'#a45cff', image:'assets/air.png', intro:'Создаём индивидуальный дизайн и выполняем аэрографию на автомобилях, мотоциклах, шлемах и других подходящих поверхностях.', items:['Разработка эскиза под конкретную поверхность','Яркие многослойные композиции и плавные переходы','Аэрография авто, мото, шлемов и отдельных элементов','Финишная защита покрытия при необходимости'], fits:'Автомобили, мотоциклы, шлемы, панели, элементы интерьера и другие поверхности.', process:'Осматриваем поверхность → обсуждаем идею → готовим эскиз → выполняем роспись → наносим защитный финиш при необходимости.'},
    'сувенирная продукция': {accent:'#ff8a00', image:'assets/souvenir.png', intro:'Изготавливаем персонализированные подарки и сувенирную продукцию с вашим изображением, логотипом или дизайном.', items:['Кружки и другая сувенирная продукция','Футболки и текстиль с индивидуальным дизайном','Подарки для друзей, мероприятий и компаний','Подготовка макета под выбранный формат изделия'], fits:'Подарки, корпоративная продукция, памятные сувениры, брендированные изделия.', process:'Выбираем изделие → получаем дизайн → проверяем макет → изготавливаем → проверяем качество и упаковываем.'}
  };
  const norm=v=>String(v||'').toLowerCase().replace(/ё/g,'е').replace(/[–—]/g,'-').trim();
  const find=title=>{const t=norm(title);return Object.keys(services).find(k=>t.includes(k))||Object.keys(services).find(k=>k.includes(t));};
  const style=document.createElement('style');style.textContent=`
    .service-fullscreen{position:fixed;inset:0;z-index:1000;display:none;padding:18px;background:rgba(2,3,7,.93);backdrop-filter:blur(14px);overflow:auto}.service-fullscreen.open{display:flex;align-items:center;justify-content:center}.service-fullscreen__card{position:relative;width:min(1480px,100%);min-height:min(860px,calc(100vh - 36px));display:grid;grid-template-columns:minmax(360px,.9fr) minmax(480px,1.1fr);overflow:hidden;background:linear-gradient(135deg,#0b1018,#111722 52%,#080b10);border:1px solid rgba(255,255,255,.18);border-radius:22px;box-shadow:0 35px 120px rgba(0,0,0,.8),inset 0 1px 0 rgba(255,255,255,.06)}
    .service-fullscreen__visual{position:relative;min-height:100%;background:#05070b;overflow:hidden}.service-fullscreen__visual:after{content:'';position:absolute;inset:auto 0 0;height:42%;background:linear-gradient(transparent,rgba(3,4,8,.95));pointer-events:none}.service-fullscreen__visual img{width:100%;height:100%;min-height:100%;object-fit:cover;display:block;filter:saturate(1.08) contrast(1.05)}.service-fullscreen__glow{position:absolute;inset:12%;border-radius:50%;filter:blur(55px);opacity:.2;pointer-events:none}.service-fullscreen__content{position:relative;padding:clamp(34px,5vw,74px);overflow:auto;display:flex;flex-direction:column;justify-content:center}.service-fullscreen__eyebrow{font:800 10px/1 monospace;letter-spacing:.25em;color:#8b96a5;text-transform:uppercase;margin-bottom:16px}.service-fullscreen__title{font-size:clamp(38px,5vw,76px);line-height:.94;letter-spacing:-.055em;margin:0 0 22px;color:#fff}.service-fullscreen__accent{height:4px;width:110px;border-radius:99px;margin-bottom:25px;box-shadow:0 0 25px currentColor}.service-fullscreen__intro{max-width:760px;color:#c5ccd5;font-size:16px;line-height:1.75;margin:0 0 28px}.service-fullscreen__grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:4px 0 28px}.service-fullscreen__block{padding:18px;border:1px solid rgba(255,255,255,.11);border-radius:12px;background:rgba(255,255,255,.035)}.service-fullscreen__block h3{font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:#fff;margin:0 0 11px}.service-fullscreen__block p{font-size:12px;line-height:1.65;color:#aab4c0;margin:0}.service-fullscreen__list{padding:0;margin:0;list-style:none;display:grid;gap:9px}.service-fullscreen__list li{font-size:12px;line-height:1.5;color:#d3d8df;padding-left:20px;position:relative}.service-fullscreen__list li:before{content:'+';position:absolute;left:0;top:0;font-weight:900}.service-fullscreen__actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:4px}.service-fullscreen__action{display:inline-flex;align-items:center;justify-content:center;min-height:46px;padding:0 20px;border-radius:7px;border:1px solid rgba(255,255,255,.18);font-size:11px;font-weight:900;text-transform:uppercase;letter-spacing:.05em;color:#fff;background:#111720;cursor:pointer}.service-fullscreen__action.primary{border:0;color:#050507;background:linear-gradient(90deg,#00bfff,#5f9dff);box-shadow:0 10px 35px rgba(0,191,255,.2)}.service-fullscreen__close{position:absolute;z-index:3;right:18px;top:18px;width:46px;height:46px;border-radius:50%;border:1px solid rgba(255,255,255,.22);background:rgba(8,11,16,.8);color:#fff;font-size:25px;cursor:pointer;backdrop-filter:blur(8px);transition:.2s}.service-fullscreen__close:hover{transform:rotate(90deg);border-color:rgba(255,255,255,.5)}body.service-modal-open{overflow:hidden}.service-fullscreen__hint{position:absolute;left:28px;bottom:24px;z-index:2;font:700 9px/1 monospace;letter-spacing:.16em;color:rgba(255,255,255,.55);text-transform:uppercase}
    @media(max-width:900px){.service-fullscreen{padding:0}.service-fullscreen__card{min-height:100vh;border-radius:0;border:0;grid-template-columns:1fr;grid-template-rows:34vh auto}.service-fullscreen__visual{min-height:34vh}.service-fullscreen__visual img{min-height:34vh}.service-fullscreen__content{padding:30px 22px 38px;justify-content:flex-start}.service-fullscreen__title{font-size:clamp(34px,10vw,52px)}.service-fullscreen__intro{font-size:14px}.service-fullscreen__grid{grid-template-columns:1fr}.service-fullscreen__close{top:12px;right:12px}}
  `;document.head.appendChild(style);
  const modal=document.createElement('div');modal.className='service-fullscreen';modal.setAttribute('aria-hidden','true');modal.innerHTML='<div class="service-fullscreen__card"><button class="service-fullscreen__close" type="button" aria-label="Закрыть">×</button><div class="service-fullscreen__visual"><img alt=""><div class="service-fullscreen__glow"></div><div class="service-fullscreen__hint">ESC — закрыть</div></div><div class="service-fullscreen__content"></div></div>';document.body.appendChild(modal);
  const content=modal.querySelector('.service-fullscreen__content'),image=modal.querySelector('.service-fullscreen__visual img'),glow=modal.querySelector('.service-fullscreen__glow');
  const close=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('service-modal-open')};
  const open=service=>{const title=service.querySelector('h3')?.textContent?.trim()||'Услуга',key=find(title);if(!key)return;const d=services[key];image.src=service.querySelector('.service-img')?.getAttribute('src')||d.image;image.alt=title;glow.style.background=d.accent;content.innerHTML=`<div class="service-fullscreen__eyebrow">3D-ARTPRINT · УСЛУГА</div><h2 class="service-fullscreen__title">${title}</h2><div class="service-fullscreen__accent" style="background:${d.accent};color:${d.accent}"></div><p class="service-fullscreen__intro">${d.intro}</p><div class="service-fullscreen__grid"><div class="service-fullscreen__block"><h3>Что входит</h3><ul class="service-fullscreen__list">${d.items.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="service-fullscreen__block"><h3>Подходит для</h3><p>${d.fits}</p><br><h3>Как работаем</h3><p>${d.process}</p></div></div><div class="service-fullscreen__actions"><a class="service-fullscreen__action primary" href="#order">Рассчитать / заказать →</a><button class="service-fullscreen__action" type="button" data-service-close>Вернуться к услугам</button></div>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('service-modal-open')};
  document.addEventListener('click',e=>{const service=e.target.closest('.service');if(!service||!document.querySelector('.service-grid, .services')||e.target.closest('.service-fullscreen'))return;e.preventDefault();e.stopPropagation();open(service)},true);
  modal.addEventListener('click',e=>{if(e.target===modal||e.target.closest('.service-fullscreen__close')||e.target.closest('[data-service-close]'))close();if(e.target.closest('.service-fullscreen__action.primary'))close()});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('open'))close()});
})();
